# Generated by Django 5.2.17 on 2026-08-09 21:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ra",
                    models.FloatField(
                        help_text="Right ascension in decimal degrees.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(360.0),
                        ],
                        verbose_name="RA",
                    ),
                ),
                (
                    "decl",
                    models.FloatField(
                        help_text="Declination in decimal degrees.",
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="Dec",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Broker-assigned object name or ID.", max_length=30
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="Where the transient came from, e.g. 'lasair'.",
                        max_length=30,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Object page at the origin broker."
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="transients__name_cdd677_idx"),
                    models.Index(
                        fields=["origin"], name="transients__origin_af8efe_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "origin"), name="uniq_transient_name_origin"
                    )
                ],
            },
        ),
    ]
