# Generated by Django 5.2.17 on 2026-08-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transient",
            name="origin",
            field=models.CharField(
                help_text="Where the transient came from — a broker name or the URL of the filter that selected it.",
                max_length=75,
            ),
        ),
    ]
