# Generated by Django 5.2.17 on 2026-08-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transients", "0002_alter_transient_origin"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transient",
            new_name="transients_name_f9b4d8_idx",
            old_name="transients__name_cdd677_idx",
        ),
        migrations.RenameIndex(
            model_name="transient",
            new_name="transients_origin_d90f3d_idx",
            old_name="transients__origin_af8efe_idx",
        ),
        migrations.AlterModelTable(
            name="transient",
            table="transients",
        ),
    ]
