# Generated by Django 5.2.17 on 2026-08-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transients", "0003_rename_transient_table_to_transients"),
    ]

    operations = [
        migrations.AddField(
            model_name="transient",
            name="sherlock_classification",
            field=models.CharField(
                blank=True,
                help_text="Sherlock's classification code for this transient, e.g. SN, NT, VS, AGN.",
                max_length=10,
            ),
        ),
    ]
