# Generated by Django 5.2.17 on 2026-08-10 12:14

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    """*rewrite the rows 0004 created as "" so NULL is the only empty state*"""
    Transient = apps.get_model("transients", "Transient")
    Transient.objects.filter(sherlock_classification="").update(sherlock_classification=None)


def null_to_blank(apps, schema_editor):
    """*reverse of ``blank_to_null``, so the field can go back to NOT NULL*"""
    Transient = apps.get_model("transients", "Transient")
    Transient.objects.filter(sherlock_classification=None).update(sherlock_classification="")


class Migration(migrations.Migration):

    dependencies = [
        ("transients", "0004_add_sherlock_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transient",
            name="sherlock_classification",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Sherlock's classification code for this transient, e.g. SN, NT, VS, AGN.",
                max_length=10,
                null=True,
            ),
        ),
        # THE COLUMN MUST BE NULLABLE BEFORE THE BACKFILL CAN WRITE NULL INTO IT.
        migrations.RunPython(blank_to_null, null_to_blank),
    ]
