# Generated by Django 5.2.17 on 2026-08-11 08:30

from django.db import migrations, models

# EVERY ROW WRITTEN BEFORE THE SPLIT CAME FROM THE SAME LASAIR FILTER, AND THE
# OLD `origin` COLUMN HELD ITS URL. THE NAME IS NOT DERIVABLE FROM ANYTHING IN
# THE DATABASE, SO IT IS SPELLED OUT HERE.
BACKFILL_ORIGIN_NAME = "lasair filter"


def name_the_existing_origins(apps, schema_editor):
    """*give every pre-split row the name its origin URL never carried*"""
    Transient = apps.get_model("transients", "Transient")
    Transient.objects.filter(origin_name="").update(origin_name=BACKFILL_ORIGIN_NAME)


def unname_the_origins(apps, schema_editor):
    """*reverse of ``name_the_existing_origins``*"""
    Transient = apps.get_model("transients", "Transient")
    Transient.objects.filter(origin_name=BACKFILL_ORIGIN_NAME).update(origin_name="")


class Migration(migrations.Migration):

    dependencies = [
        ("transients", "0005_sherlock_classification_null"),
    ]

    # makemigrations OFFERS RemoveField + AddField HERE, WHICH WOULD DROP THE
    # COLUMN AND EVERY origin URL WITH IT. RenameField KEEPS THE DATA: THE OLD
    # `origin` VALUES ARE ALREADY THE FILTER URLS THIS SPLIT WANTS.
    operations = [
        migrations.RemoveConstraint(
            model_name="transient",
            name="uniq_transient_name_origin",
        ),
        migrations.RemoveIndex(
            model_name="transient",
            name="transients_origin_d90f3d_idx",
        ),
        migrations.RenameField(
            model_name="transient",
            old_name="origin",
            new_name="origin_url",
        ),
        migrations.AlterField(
            model_name="transient",
            name="origin_url",
            field=models.URLField(
                blank=True,
                help_text="The broker filter or feed that selected this transient.",
            ),
        ),
        migrations.AddField(
            model_name="transient",
            name="origin_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable name for where the transient came from, e.g. 'lasair filter'.",
                max_length=75,
            ),
            # THE DEFAULT IS ONLY THERE TO FILL THE EXISTING ROWS AS THE COLUMN
            # IS ADDED; THE MODEL DOES NOT DECLARE ONE.
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="transient",
            index=models.Index(
                fields=["origin_name"], name="transients_origin__b51ad1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transient",
            constraint=models.UniqueConstraint(
                fields=("name", "origin_url"), name="uniq_transient_name_origin_url"
            ),
        ),
        # THE COLUMN HAS TO EXIST BEFORE THE BACKFILL CAN WRITE INTO IT.
        migrations.RunPython(name_the_existing_origins, unname_the_origins),
    ]
