# Generated by Django 5.2.17 on 2026-08-10 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transients", "0002_alter_transient_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SherlockVetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sherlock_version", models.CharField(max_length=15)),
                ("sherlock_correct", models.BooleanField(default=None, null=True)),
                (
                    "sherlock_correct_host",
                    models.IntegerField(
                        blank=True,
                        help_text="Rank of the correct host among Sherlock's crossmatches.",
                        null=True,
                    ),
                ),
                ("user_comment", models.TextField(blank=True)),
                (
                    "transient",
                    models.ForeignKey(
                        db_column="transients_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vettings",
                        to="transients.transient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vettings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sherlock_vetting",
                "ordering": ["transient__name"],
                "indexes": [
                    models.Index(
                        fields=["sherlock_version", "sherlock_correct"],
                        name="sherlock_ve_sherloc_24008c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transient", "sherlock_version"),
                        name="uniq_vetting_transient_version",
                    )
                ],
            },
        ),
    ]
