# Generated by Django 5.2.17 on 2026-08-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vetting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sherlockvetting",
            name="corrected_classification",
            field=models.CharField(
                blank=True,
                help_text="What the classification should have been, when the association was right.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sherlockvetting",
            name="incorrect_reason",
            field=models.CharField(
                blank=True,
                help_text="Why Sherlock got this transient wrong.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="VettingReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sherlock_version", models.CharField(max_length=15)),
                ("reason", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vetting_reasons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sherlock_vetting_reasons",
                "ordering": ["reason"],
                "indexes": [
                    models.Index(
                        fields=["sherlock_version"],
                        name="sherlock_ve_sherloc_5b96d1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sherlock_version", "reason"),
                        name="uniq_vetting_reason_version",
                    )
                ],
            },
        ),
    ]
