# Generated by Django 5.2.17 on 2026-08-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transients", "0005_sherlock_classification_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="SherlockClassification",
            fields=[
                (
                    "transient",
                    models.OneToOneField(
                        db_column="transient_object_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="sherlock_result",
                        serialize=False,
                        to="transients.transient",
                    ),
                ),
                ("classification", models.CharField(max_length=45, null=True)),
                ("annotation", models.TextField(null=True)),
                ("summary", models.CharField(max_length=50, null=True)),
                (
                    "separation_arcsec",
                    models.FloatField(db_column="separationArcsec", null=True),
                ),
                (
                    "match_verified",
                    models.IntegerField(db_column="matchVerified", null=True),
                ),
            ],
            options={
                "db_table": "sherlock_classifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SherlockCrossmatch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rank", models.IntegerField(null=True)),
                ("merged_rank", models.IntegerField(null=True)),
                ("rank_score", models.FloatField(db_column="rankScore", null=True)),
                ("catalogue_object_id", models.CharField(max_length=200, null=True)),
                ("catalogue_table_name", models.CharField(max_length=100, null=True)),
                ("catalogue_object_type", models.CharField(max_length=45, null=True)),
                (
                    "catalogue_object_subtype",
                    models.CharField(max_length=45, null=True),
                ),
                ("association_type", models.CharField(max_length=45, null=True)),
                (
                    "classification_reliability",
                    models.IntegerField(
                        db_column="classificationReliability", null=True
                    ),
                ),
                (
                    "separation_arcsec",
                    models.FloatField(db_column="separationArcsec", null=True),
                ),
                (
                    "north_separation_arcsec",
                    models.FloatField(db_column="northSeparationArcsec", null=True),
                ),
                (
                    "east_separation_arcsec",
                    models.FloatField(db_column="eastSeparationArcsec", null=True),
                ),
                ("physical_separation_kpc", models.FloatField(null=True)),
                ("sm_axis_arcsec", models.FloatField(null=True)),
                ("z", models.FloatField(null=True)),
                ("photo_z", models.FloatField(db_column="photoZ", null=True)),
                ("direct_distance", models.FloatField(null=True)),
                ("best_distance", models.FloatField(null=True)),
                ("best_distance_flag", models.CharField(max_length=100, null=True)),
                ("best_distance_source", models.CharField(max_length=100, null=True)),
                (
                    "transient_abs_mag",
                    models.FloatField(db_column="transientAbsMag", null=True),
                ),
                ("ra_deg", models.FloatField(db_column="raDeg", null=True)),
                ("dec_deg", models.FloatField(db_column="decDeg", null=True)),
                ("mag_R", models.FloatField(db_column="R", null=True)),
                ("mag_r", models.FloatField(db_column="_r", null=True)),
                ("mag_G", models.FloatField(db_column="G", null=True)),
                ("mag_V", models.FloatField(db_column="V", null=True)),
                ("mag_g", models.FloatField(db_column="_g", null=True)),
                ("mag_B", models.FloatField(db_column="B", null=True)),
                ("mag_I", models.FloatField(db_column="I", null=True)),
                ("mag_i", models.FloatField(db_column="_i", null=True)),
                ("mag_z", models.FloatField(db_column="_z", null=True)),
                ("mag_J", models.FloatField(db_column="J", null=True)),
                ("mag_H", models.FloatField(db_column="H", null=True)),
                ("mag_K", models.FloatField(db_column="K", null=True)),
                ("mag_U", models.FloatField(db_column="U", null=True)),
                ("mag_u", models.FloatField(db_column="_u", null=True)),
                ("mag_y", models.FloatField(db_column="_y", null=True)),
                ("mag_W1", models.FloatField(db_column="W1", null=True)),
                ("mag_unk", models.FloatField(db_column="unkMag", null=True)),
            ],
            options={
                "verbose_name_plural": "sherlock crossmatches",
                "db_table": "sherlock_crossmatches",
                "ordering": ["rank", "merged_rank", "id"],
                "managed": False,
            },
        ),
    ]
